# Generated by Django 4.2.2 on 2023-08-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
