# Generated by Django 4.2.2 on 2023-08-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_workday_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='workday',
            field=models.DateField(),
        ),
    ]
