# Generated by Django 4.2.2 on 2023-08-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_workday_workday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workday',
            options={'ordering': ['workday']},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.workday'),
        ),
    ]
