# Generated by Django 4.2.2 on 2023-08-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_attendance_options_alter_workday_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workday',
            old_name='start_time',
            new_name='late_time',
        ),
    ]
