# Generated by Django 4.2.2 on 2023-08-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_start_time_workday_late_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
