# Generated by Django 4.2.2 on 2023-08-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_attendance_check_in'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workday',
            options={'ordering': ['-workday']},
        ),
        migrations.RemoveField(
            model_name='leave',
            name='duration',
        ),
        migrations.AddField(
            model_name='leave',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('in Review', 'in Review')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick leave', 'Sick leave'), ('Vacation', 'Vacation')], max_length=10),
        ),
    ]
