# Generated by Django 4.2.2 on 2023-08-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_workday_options_remove_leave_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('in Review', 'in Review')], default='in Review', max_length=50),
        ),
    ]
