# Generated by Django 4.2.2 on 2023-08-24 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_alter_leave_end_date_alter_leave_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='Appproved_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approved_on',
            field=models.DateField(blank=True),
        ),
    ]
