# Generated by Django 4.2.2 on 2023-08-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_attendance_check_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='Appproved_by',
            new_name='reviewed_by',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='approved_on',
            new_name='reviewed_on',
        ),
    ]
