# Generated by Django 4.2.2 on 2023-08-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_appproved_by_leave_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='avatar.png', upload_to='profiles/'),
        ),
    ]
