# Generated by Django 4.2.2 on 2023-08-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(),
        ),
    ]
